[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  '@account-abstraction/=lib/account-abstraction/contracts/',
  '@solady/=lib/solady/src/'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
